POST  http://localhost:3003/class
Content-Type: application/json

{
    "name": "Teste zero",
    "unit": 0
}

###
GET http://localhost:3003/class

###
PUT http://localhost:3003/class/1
Content-Type: application/json

{
    "unit": 5
}